#!/bin/sh
#
# chkconfig: - 85 15
# description: HA-Proxy is a TCP/HTTP reverse proxy which is particularly suited \
#              for high availability environments.
# processname: haproxy
# config: /etc/haproxy.cfg
# pidfile: /var/run/haproxy.pid

# Script Author: Simon Matter <simon.matter@invoca.ch>
# Version: 2004060600

RETVAL=0

start() {
  /usr/sbin/haproxy -c -q -f /etc/haproxy.cfg
  if [ $? -ne 0 ]; then
    echo "Errors found in configuration file, check it with 'haproxy check'."
    return 1
  fi

  echo -n "Starting haproxy: "
	start-stop-daemon --start --pidfile /var/run/haproxy.pid \
		--exec /usr/sbin/haproxy -- -f /etc/haproxy.cfg -D -p /var/run/haproxy.pid \
		  || return 2
		
  return 0
}

stop() {
  echo -n "Shutting down haproxy: "

	start-stop-daemon --retry 5 --oknodo --stop --quiet --pidfile /var/run/haproxy.pid \
		--exec /usr/sbin/haproxy  > /dev/null 2>&1

	echo "."
}

restart() {
  /usr/sbin/haproxy -c -q -f /etc/haproxy.cfg
  if [ $? -ne 0 ]; then
    echo "Errors found in configuration file, check it with 'haproxy check'."
    return 1
  fi
  stop
  start
}

check() {
  /usr/sbin/haproxy -c -q -V -f /etc/haproxy.cfg
}

# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  reload)
    restart
    ;;
  check)
    check
    ;;
  *)
    echo $"Usage: haproxy {start|stop|restart|reload|check}"
    RETVAL=1
esac
 
exit $RETVAL
