--- 
user: reeds
group: www-data
cwd: /u/apps/reeds/current
log_file: /u/apps/reeds/shared/log/mongrel.log
port: "8000"
environment: production
address: 127.0.0.1
pid_file: /u/apps/reeds/shared/pids/mongrel.pid
config_script: /u/apps/reeds/current/lib/health_check_handler.rb
servers: 2
