--- 
user: mauricio
group: www-data
cwd: /var/www/apps/reeds/current
log_file: /var/www/apps/reeds/shared/log/mongrel.log
port: "8000"
environment: production
address: 127.0.0.1
pid_file: /var/www/apps/reeds/shared/pids/mongrel.pid
servers: 2